// 각 컬렉션의 필드 정의
export type FieldType = 'text' | 'number' | 'select' | 'textarea' | 'json';

export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: string[]; // select용
  placeholder?: string;
}

export interface CollectionDef {
  name: string;         // MongoDB 컬렉션명
  label: string;        // 한글 표시명
  emoji: string;
  fields: FieldDef[];
  tableColumns: string[]; // 테이블에 보여줄 주요 컬럼
}

const GRADE_OPTIONS = ['common', 'uncommon', 'rare', 'epic', 'legendary'];

export const collections: CollectionDef[] = [
  {
    name: 'gem_master',
    label: '보석 마스터',
    emoji: '💎',
    tableColumns: ['gem_code', 'name', 'prefix', 'grade', 'value'],
    fields: [
      { key: 'gem_code', label: '보석 코드', type: 'text', required: true, placeholder: 'gem_fire_001' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'prefix', label: '접두사', type: 'text' },
      { key: 'grade', label: '등급', type: 'select', options: GRADE_OPTIONS },
      { key: 'value', label: '가치', type: 'number' },
      { key: 'trait_1', label: '특성1', type: 'text', placeholder: 'trait_heat' },
      { key: 'trait_1_lv', label: '특성1 레벨', type: 'text' },
      { key: 'trait_2', label: '특성2', type: 'text' },
      { key: 'trait_2_lv', label: '특성2 레벨', type: 'text' },
      { key: 'trait_3', label: '특성3', type: 'text' },
      { key: 'trait_3_lv', label: '특성3 레벨', type: 'text' },
      { key: 'trait_4', label: '특성4', type: 'text' },
      { key: 'trait_4_lv', label: '특성4 레벨', type: 'text' },
      { key: 'bonus_stat_1', label: '보너스 스탯1', type: 'text', placeholder: 'atk+5' },
      { key: 'bonus_stat_2', label: '보너스 스탯2', type: 'text' },
      { key: 'description', label: '설명', type: 'textarea' },
    ],
  },
  {
    name: 'item_master_food',
    label: '아이템 - 음식/포션',
    emoji: '🧪',
    tableColumns: ['item_code', 'name', 'item_type', 'grade'],
    fields: [
      { key: 'item_code', label: '아이템 코드', type: 'text', required: true, placeholder: 'food_potion_hp_sm' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'item_type', label: '타입', type: 'select', options: ['potion', 'food'] },
      { key: 'grade', label: '등급', type: 'select', options: GRADE_OPTIONS },
      { key: 'upgrade_to', label: '업그레이드 대상', type: 'text' },
      { key: 'upgrade_required', label: '업그레이드 비용', type: 'number' },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'stats', label: '스탯 (JSON)', type: 'json', placeholder: '{"hp_recover":50,"mp_recover":0,"buff_type":null,"buff_value":0,"buff_duration":0}' },
    ],
  },
  {
    name: 'item_master_heart',
    label: '아이템 - 심장',
    emoji: '❤️',
    tableColumns: ['item_code', 'name', 'grade'],
    fields: [
      { key: 'item_code', label: '아이템 코드', type: 'text', required: true, placeholder: 'heart_basic_001' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'item_type', label: '타입', type: 'text', placeholder: 'heart' },
      { key: 'grade', label: '등급', type: 'select', options: GRADE_OPTIONS },
      { key: 'upgrade_to', label: '업그레이드 대상', type: 'text' },
      { key: 'upgrade_required', label: '업그레이드 비용', type: 'number' },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'stats', label: '스탯 (JSON)', type: 'json', placeholder: '{"hp_base":50,"def_base":3}' },
    ],
  },
  {
    name: 'item_master_material',
    label: '아이템 - 재료',
    emoji: '🪨',
    tableColumns: ['item_code', 'name', 'item_type', 'grade'],
    fields: [
      { key: 'item_code', label: '아이템 코드', type: 'text', required: true, placeholder: 'mat_iron_ore' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'item_type', label: '타입', type: 'select', options: ['mineral', 'material', 'seed', 'plant', 'baby_animal', 'raw_gem', 'polish'] },
      { key: 'grade', label: '등급', type: 'select', options: GRADE_OPTIONS },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'stats', label: '스탯 (JSON)', type: 'json', placeholder: '{"mineral_bonus":{"atk":0.2,"durability":3}} 또는 null' },
    ],
  },
  {
    name: 'item_master_weapon',
    label: '아이템 - 무기',
    emoji: '⚔️',
    tableColumns: ['item_code', 'name', 'grade', 'atk', 'durability_max'],
    fields: [
      { key: 'item_code', label: '아이템 코드', type: 'text', required: true, placeholder: 'wpn_sword_001' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'item_type', label: '타입', type: 'text', placeholder: 'weapon' },
      { key: 'grade', label: '등급', type: 'select', options: GRADE_OPTIONS },
      { key: 'atk', label: '공격력', type: 'number' },
      { key: 'durability_max', label: '최대 내구도', type: 'number' },
      { key: 'elem_slot_1', label: '속성 슬롯1', type: 'select', options: ['', 'fire', 'water', 'ice', 'thunder', 'wind', 'earth'] },
      { key: 'elem_slot_2', label: '속성 슬롯2', type: 'select', options: ['', 'fire', 'water', 'ice', 'thunder', 'wind', 'earth'] },
      { key: 'weapon_skill', label: '무기 스킬 코드', type: 'text', placeholder: 'wsk_iron_will' },
      { key: 'upgrade_to', label: '업그레이드 대상', type: 'text' },
      { key: 'upgrade_required', label: '업그레이드 비용', type: 'number' },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'stats', label: '스탯 (JSON)', type: 'json', placeholder: '{"atk_base":5,"crit_rate":2,"crit_dmg":110}' },
    ],
  },
  {
    name: 'monster_master',
    label: '몬스터 마스터',
    emoji: '👾',
    tableColumns: ['monster_code', 'name', 'emoji', 'grade', 'hp', 'atk'],
    fields: [
      { key: 'monster_code', label: '몬스터 코드', type: 'text', required: true, placeholder: 'mon_east_star_slime' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'emoji', label: '이모지', type: 'text', placeholder: '🟡' },
      { key: 'grade', label: '등급', type: 'select', options: GRADE_OPTIONS },
      { key: 'place_codes', label: '출현 장소 (JSON 배열)', type: 'json', placeholder: '["east_star_01"]' },
      { key: 'hp', label: 'HP', type: 'number' },
      { key: 'mp', label: 'MP', type: 'number' },
      { key: 'atk', label: 'ATK', type: 'number' },
      { key: 'def', label: 'DEF', type: 'number' },
      { key: 'mag_atk', label: 'MAG ATK', type: 'number' },
      { key: 'mag_def', label: 'MAG DEF', type: 'number' },
      { key: 'armor_pen', label: '방관', type: 'number' },
      { key: 'mag_pen', label: '마관', type: 'number' },
      { key: 'crit_rate', label: '치명타율', type: 'number' },
      { key: 'crit_dmg', label: '치명타뎀', type: 'number' },
      { key: 'dodge', label: '회피', type: 'number' },
      { key: 'atk_spd', label: '공속', type: 'number' },
      { key: 'shield', label: '쉴드', type: 'number' },
      { key: 'fire_atk', label: '화공', type: 'number' },
      { key: 'fire_def', label: '화방', type: 'number' },
      { key: 'ice_atk', label: '빙공', type: 'number' },
      { key: 'ice_def', label: '빙방', type: 'number' },
      { key: 'thunder_atk', label: '뇌공', type: 'number' },
      { key: 'thunder_def', label: '뇌방', type: 'number' },
      { key: 'burn_chance', label: '화상%', type: 'number' },
      { key: 'freeze_chance', label: '빙결%', type: 'number' },
      { key: 'stun_chance', label: '기절%', type: 'number' },
      { key: 'drop_gold_min', label: '골드(최소)', type: 'number' },
      { key: 'drop_gold_max', label: '골드(최대)', type: 'number' },
      { key: 'drops', label: '드롭 (JSON)', type: 'json', placeholder: '[{"item_code":"mat_slime_jelly","chance":60}]' },
    ],
  },
  {
    name: 'prefix_master',
    label: '접두사 마스터',
    emoji: '✨',
    tableColumns: ['prefix_code', 'name', 'grade_bonus', 'effect_1'],
    fields: [
      { key: 'prefix_code', label: '접두사 코드', type: 'text', required: true, placeholder: 'pf_shining' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'grade_bonus', label: '등급 보너스', type: 'number' },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'effect_1', label: '효과1', type: 'text', placeholder: 'trait_boost_pct+10' },
      { key: 'effect_2', label: '효과2', type: 'text' },
    ],
  },
  {
    name: 'region_master',
    label: '지역 마스터',
    emoji: '🗺️',
    tableColumns: ['place_code', 'region_name', 'sub_region_name', 'place_name', 'place_level'],
    fields: [
      { key: 'region_code', label: '지역 코드', type: 'text', required: true, placeholder: 'east' },
      { key: 'region_type', label: '지역 타입', type: 'select', options: ['adventure', 'mine'] },
      { key: 'region_name', label: '지역명', type: 'text', required: true },
      { key: 'region_emoji', label: '지역 이모지', type: 'text' },
      { key: 'region_accent', label: '지역 색상', type: 'text', placeholder: '#e74c3c' },
      { key: 'region_desc', label: '지역 설명', type: 'textarea' },
      { key: 'region_order', label: '지역 순서', type: 'number' },
      { key: 'sub_region_code', label: '서브 지역 코드', type: 'text', required: true },
      { key: 'sub_region_name', label: '서브 지역명', type: 'text', required: true },
      { key: 'sub_region_emoji', label: '서브 지역 이모지', type: 'text' },
      { key: 'sub_region_accent', label: '서브 지역 색상', type: 'text' },
      { key: 'sub_region_order', label: '서브 지역 순서', type: 'number' },
      { key: 'place_code', label: '장소 코드', type: 'text', required: true, placeholder: 'east_star_01' },
      { key: 'place_name', label: '장소명', type: 'text', required: true },
      { key: 'place_emoji', label: '장소 이모지', type: 'text' },
      { key: 'place_image', label: '장소 이미지', type: 'text' },
      { key: 'place_desc', label: '장소 설명', type: 'textarea' },
      { key: 'place_lore', label: '장소 로어', type: 'textarea' },
      { key: 'place_monsters', label: '장소 몬스터 (JSON)', type: 'json', placeholder: '["별빛 슬라임","유성 박쥐"]' },
      { key: 'place_features', label: '장소 특징 (JSON)', type: 'json', placeholder: '["야간 시야 확보"]' },
      { key: 'place_level', label: '장소 레벨', type: 'text', placeholder: 'Lv. 1~5' },
      { key: 'place_order', label: '장소 순서', type: 'number' },
      { key: 'required_rank', label: '필요 랭크', type: 'text' },
    ],
  },
  {
    name: 'seed_achievement',
    label: '업적',
    emoji: '🏆',
    tableColumns: ['achievement_code', 'name', 'achievement_type', 'required_count'],
    fields: [
      { key: 'achievement_code', label: '업적 코드', type: 'text', required: true, placeholder: 'ach_first_login' },
      { key: 'achievement_type', label: '업적 타입', type: 'select', options: ['general', 'combat', 'craft'] },
      { key: 'count', label: '현재 카운트', type: 'number' },
      { key: 'unlocked', label: '해금 여부 (0/1)', type: 'number' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'required_count', label: '필요 카운트', type: 'number', required: true },
    ],
  },
  {
    name: 'seed_forge_recipe',
    label: '제련 레시피',
    emoji: '🔨',
    tableColumns: ['recipe_code', 'name', 'craft_type', 'grade', 'base_success_rate'],
    fields: [
      { key: 'recipe_code', label: '레시피 코드', type: 'text', required: true, placeholder: 'forge_iron_sword' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'result_item_code', label: '결과 아이템 코드', type: 'text', required: true },
      { key: 'craft_type', label: '제작 타입', type: 'select', options: ['weapon', 'heart', 'potion', 'food', 'polish'] },
      { key: 'grade', label: '등급', type: 'select', options: GRADE_OPTIONS },
      { key: 'max_level', label: '최대 레벨', type: 'number' },
      { key: 'base_success_rate', label: '기본 성공률', type: 'number' },
      { key: 'mineral_cost', label: '광물 최소', type: 'number' },
      { key: 'mineral_cost_max', label: '광물 최대', type: 'number' },
      { key: 'ingredients', label: '재료 (JSON)', type: 'json', placeholder: '[{"item_code":"mat_wood_hard","quantity":1}]' },
    ],
  },
  {
    name: 'seed_guild',
    label: '길드 데이터',
    emoji: '🏛️',
    tableColumns: ['_section', 'guild_code', 'name'],
    fields: [
      { key: '_section', label: '섹션', type: 'select', options: ['guilds', 'ranks', 'quests', 'delivers', 'shop', 'kingdom_guilds', 'kingdom_quests', 'kingdom_delivers', 'kingdom_shop'], required: true },
      { key: 'data', label: '데이터 (JSON)', type: 'json', required: true, placeholder: '해당 섹션의 데이터 객체를 JSON으로 입력' },
    ],
  },
  {
    name: 'seed_rank',
    label: '랭크',
    emoji: '📊',
    tableColumns: ['rank', 'label', 'stat_points'],
    fields: [
      { key: 'rank', label: '랭크', type: 'text', required: true },
      { key: 'label', label: '라벨', type: 'text', required: true },
      { key: 'stat_points', label: '스탯 포인트', type: 'number', required: true },
    ],
  },
  {
    name: 'seed_recipe',
    label: '레시피',
    emoji: '📜',
    tableColumns: ['recipe_code', 'name', 'recipe_category', 'unlocked'],
    fields: [
      { key: 'recipe_code', label: '레시피 코드', type: 'text', required: true },
      { key: 'recipe_category', label: '카테고리', type: 'select', options: ['equip', 'food', 'skill'] },
      { key: 'recipe_sub_type', label: '서브 타입', type: 'text', placeholder: 'weapon / potion / active / passive' },
      { key: 'recipe_type', label: '레시피 타입', type: 'text', placeholder: 'weapon / food / skill / material' },
      { key: 'level', label: '레벨', type: 'number' },
      { key: 'max_level', label: '최대 레벨', type: 'number' },
      { key: 'proficiency', label: '숙련도', type: 'number' },
      { key: 'required_proficiency', label: '필요 숙련도', type: 'number' },
      { key: 'use_count', label: '사용 횟수', type: 'number' },
      { key: 'unlocked', label: '해금 (0/1)', type: 'number' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'ingredients', label: '재료 (JSON)', type: 'json', placeholder: '[{"item_code":"mat_iron_ore","quantity":5}]' },
      { key: 'result_item_code', label: '결과 아이템 코드', type: 'text' },
      { key: 'result_skill_code', label: '결과 스킬 코드', type: 'text' },
    ],
  },
  {
    name: 'skill_master',
    label: '스킬 마스터',
    emoji: '🔮',
    tableColumns: ['skill_code', 'name', 'icon', 'grade', 'mp_cost'],
    fields: [
      { key: 'skill_code', label: '스킬 코드', type: 'text', required: true, placeholder: 'sk_slash' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'icon', label: '아이콘', type: 'text', placeholder: '⚔️' },
      { key: 'mp_cost', label: 'MP 소모', type: 'number' },
      { key: 'cooldown', label: '쿨다운', type: 'number' },
      { key: 'log_message', label: '로그 메시지', type: 'text' },
      { key: 'effect_type', label: '효과 타입', type: 'select', options: ['atk_scale', 'mag_scale', 'heal', 'buff_atk', 'buff_def', 'multi_atk'] },
      { key: 'effect_value', label: '효과 값', type: 'number' },
      { key: 'effect_stat', label: '효과 스탯', type: 'text', placeholder: 'atk / magAtk / maxHp / def' },
      { key: 'effect_extra', label: '추가 효과', type: 'text', placeholder: 'burn_chance+20' },
      { key: 'grade', label: '등급', type: 'select', options: GRADE_OPTIONS },
    ],
  },
  {
    name: 'trait_master',
    label: '특성 마스터',
    emoji: '🌀',
    tableColumns: ['trait_code', 'name', 'level', 'effect_1'],
    fields: [
      { key: 'trait_code', label: '특성 코드', type: 'text', required: true, placeholder: 'trait_heat' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'level', label: '레벨', type: 'text', required: true },
      { key: 'effect_1', label: '효과1', type: 'text', placeholder: 'fire_atk+10' },
      { key: 'effect_2', label: '효과2', type: 'text' },
      { key: 'effect_3', label: '효과3', type: 'text' },
      { key: 'effect_4', label: '효과4', type: 'text' },
      { key: 'effect_5', label: '효과5', type: 'text' },
    ],
  },
  {
    name: 'weapon_skill_master',
    label: '무기 스킬 마스터',
    emoji: '🗡️',
    tableColumns: ['weapon_skill_code', 'name', 'skill_type', 'grade'],
    fields: [
      { key: 'weapon_skill_code', label: '무기 스킬 코드', type: 'text', required: true, placeholder: 'wsk_iron_will' },
      { key: 'name', label: '이름', type: 'text', required: true },
      { key: 'description', label: '설명', type: 'textarea' },
      { key: 'icon', label: '아이콘', type: 'text', placeholder: '🛡️' },
      { key: 'skill_type', label: '스킬 타입', type: 'select', options: ['passive', 'active'] },
      { key: 'mp_cost', label: 'MP 소모', type: 'number' },
      { key: 'cooldown', label: '쿨다운', type: 'number' },
      { key: 'log_message', label: '로그 메시지', type: 'text' },
      { key: 'effect_type', label: '효과 타입', type: 'select', options: ['none', 'buff_def_pct', 'atk_scale', 'mag_scale', 'multi_atk', 'multi_buff'] },
      { key: 'effect_value', label: '효과 값', type: 'number' },
      { key: 'effect_stat', label: '효과 스탯', type: 'text' },
      { key: 'effect_extra', label: '추가 효과', type: 'text', placeholder: 'burn_chance+40' },
      { key: 'grade', label: '등급', type: 'select', options: GRADE_OPTIONS },
    ],
  },
];

export function getCollection(name: string): CollectionDef | undefined {
  return collections.find((c) => c.name === name);
}
